### ISSUE TITLE
Notice: Array to string conversion  in /app/code/community/Aoe/TemplateHints/Model/Renderer/Comment.php on line 62

### ISSUE THREAD

**Issue by paales** [AOEpeople/Aoe_TemplateHints#24]
Notice: Array to string conversion  in /app/code/community/Aoe/TemplateHints/Model/Renderer/Comment.php on line 62

**Comment by winkelsdorf** [comment]
Your fix works fine here, too. Thank you! And I can't see anything preventing a merge..

By the way: Did you change something on the line-breaks between the blocks? I don't remember if that has been the same before.

I'd like to see a newline after <end> and before <start> of each block because it's easier to read. If that has not been your change, I will open an Issue with a Feature Request.

![screen shot 2015-04-28 at 13 42 27](https://cloud.githubusercontent.com/assets/1413291/7368867/b51b36c8-edac-11e4-8c57-cb31ceab3cf9.png)
